apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: NodePort
  # Each Pod in the Deployment that you created previously has below label. So the Pods in the Deployment will become members of this Service.
  selector:
    app: to-do-list
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
